[general]
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 1

[[datasets]]
resolution = 512
batch_size = 1
enable_bucket = true
bucket_no_upscale = true
bucket_reso_steps = 64
min_bucket_reso = 384
max_bucket_reso = 1024

  [[datasets.subsets]]
  image_dir = "/Users/lalala/learn/anime-armory/创作区/制漫剧/仙界闭关小能手/设定库/lora/CHAR_HE_PINGSHENG/常态/dataset"
  num_repeats = 5
  caption_extension = ".txt"
