import type { ModelCatalogItem, ModelDefinition, ModelModality } from "./types";

export const MODEL_CATALOG_UPDATED_AT = "2026-07-29";

export const TEXT_MODELS = [
  {
    id: "openai-gpt-5-6-sol",
    name: "GPT-5.6 Sol",
    provider: "OpenAI",
    modality: "text",
    description: "面向复杂专业工作、深度推理和长程 Agent 的旗舰模型。",
    availability: "api",
    tags: ["旗舰", "Agent", "复杂推理"],
    modelId: "gpt-5.6-sol",
    recommended: true,
  },
  {
    id: "openai-gpt-5-6-terra",
    name: "GPT-5.6 Terra",
    provider: "OpenAI",
    modality: "text",
    description: "在智能、速度和调用成本之间取得平衡的通用模型。",
    availability: "api",
    tags: ["均衡", "工具调用", "多模态理解"],
    modelId: "gpt-5.6-terra",
  },
  {
    id: "openai-gpt-5-6-luna",
    name: "GPT-5.6 Luna",
    provider: "OpenAI",
    modality: "text",
    description: "适合高吞吐、成本敏感型创作辅助和批处理任务。",
    availability: "api",
    tags: ["高吞吐", "低成本", "快速"],
    modelId: "gpt-5.6-luna",
  },
  {
    id: "anthropic-claude-fable-5",
    name: "Claude Fable 5",
    provider: "Anthropic",
    modality: "text",
    description: "Anthropic 面向长时间运行 Agent 与高难度推理的最高能力档。",
    availability: "api",
    tags: ["长程 Agent", "深度推理", "1M 上下文"],
    modelId: "claude-fable-5",
  },
  {
    id: "anthropic-claude-opus-5",
    name: "Claude Opus 5",
    provider: "Anthropic",
    modality: "text",
    description: "适合复杂编码、研究和企业级知识工作的旗舰模型。",
    availability: "api",
    tags: ["编码", "研究", "企业"],
    modelId: "claude-opus-5",
  },
  {
    id: "anthropic-claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "Anthropic",
    modality: "text",
    description: "兼顾响应速度与前沿智能，适合大多数创作和 Agent 工作流。",
    availability: "api",
    tags: ["均衡", "创作", "工具调用"],
    modelId: "claude-sonnet-5",
    recommended: true,
  },
  {
    id: "anthropic-claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    modality: "text",
    description: "低延迟、经济型文本与视觉理解模型。",
    availability: "api",
    tags: ["快速", "经济", "视觉理解"],
    modelId: "claude-haiku-4-5-20251001",
  },
  {
    id: "google-gemini-3-6-flash",
    name: "Gemini 3.6 Flash",
    provider: "Google",
    modality: "text",
    description: "兼顾速度与智能的稳定多模态模型，适合 Agent 和批量任务。",
    availability: "api",
    tags: ["多模态", "快速", "Agent"],
    modelId: "gemini-3.6-flash",
    recommended: true,
  },
  {
    id: "google-gemini-3-5-flash",
    name: "Gemini 3.5 Flash",
    provider: "Google",
    modality: "text",
    description: "针对持续性 Agent、编码和视觉理解优化的高性能模型。",
    availability: "api",
    tags: ["Agent", "编码", "多模态"],
    modelId: "gemini-3.5-flash",
  },
  {
    id: "google-gemini-3-1-pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    modality: "text",
    description: "面向复杂问题求解和高级 Agent 工作流的 Pro 级预览模型。",
    availability: "preview",
    tags: ["Pro", "复杂推理", "预览"],
    modelId: "gemini-3.1-pro-preview",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    modality: "text",
    description: "支持思考模式与 1M 上下文的旗舰推理和 Agent 模型。",
    availability: "api",
    tags: ["1M 上下文", "思考模式", "Agent"],
    modelId: "deepseek-v4-pro",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    modality: "text",
    description: "保留强推理能力，同时面向更快响应和更低调用成本。",
    availability: "api",
    tags: ["高性价比", "快速", "1M 上下文"],
    modelId: "deepseek-v4-flash",
  },
  {
    id: "alibaba-qwen-3-7-max",
    name: "Qwen3.7 Max",
    provider: "阿里云",
    modality: "text",
    description: "千问系列旗舰模型，适合复杂多步骤推理和生产任务。",
    availability: "api",
    tags: ["旗舰", "推理", "中文"],
    modelId: "qwen3.7-max",
  },
  {
    id: "alibaba-qwen-3-7-plus",
    name: "Qwen3.7 Plus",
    provider: "阿里云",
    modality: "text",
    description: "兼顾效果、速度和成本的通用多模态模型。",
    availability: "api",
    tags: ["均衡", "多模态", "中文"],
    modelId: "qwen3.7-plus",
    recommended: true,
  },
  {
    id: "alibaba-qwen-3-7-flash",
    name: "Qwen3.7 Flash",
    provider: "阿里云",
    modality: "text",
    description: "面向轻量任务、实时交互和批量处理的低成本模型。",
    availability: "api",
    tags: ["快速", "低成本", "批处理"],
    modelId: "qwen3.7-flash",
  },
  {
    id: "bytedance-seed-2-pro",
    name: "Seed2.0 Pro",
    provider: "字节跳动 Seed",
    modality: "text",
    description: "针对复杂工作流、长链推理和多模态 Agent 优化。",
    availability: "api",
    tags: ["多模态", "长链推理", "Agent"],
  },
  {
    id: "bytedance-seed-2-lite",
    name: "Seed2.0 Lite",
    provider: "字节跳动 Seed",
    modality: "text",
    description: "适合生产部署的质量与速度均衡档。",
    availability: "api",
    tags: ["生产级", "均衡", "多模态"],
  },
  {
    id: "zhipu-glm-5-2",
    name: "GLM-5.2",
    provider: "智谱 AI",
    modality: "text",
    description: "支持 1M 上下文与 128K 输出的长程任务旗舰模型。",
    availability: "api",
    tags: ["1M 上下文", "长程任务", "中文"],
    modelId: "glm-5.2",
  },
  {
    id: "moonshot-kimi-k2-5",
    name: "Kimi K2.5",
    provider: "Moonshot AI",
    modality: "text",
    description: "面向长文档、视觉输入和 Agent 任务的多模态模型。",
    availability: "api",
    tags: ["多模态", "长文档", "Agent"],
    modelId: "kimi-k2.5",
  },
  {
    id: "minimax-m2-7",
    name: "MiniMax M2.7",
    provider: "MiniMax",
    modality: "text",
    description: "MiniMax 面向 Agent 推理与工具工作的通用文本模型。",
    availability: "api",
    tags: ["Agent", "推理", "工具调用"],
    modelId: "MiniMax-M2.7",
  },
  {
    id: "xai-grok-4-3",
    name: "Grok 4.3",
    provider: "xAI",
    modality: "text",
    description: "支持 1M 上下文、可配置推理和 Agent 工具调用。",
    availability: "api",
    tags: ["1M 上下文", "工具调用", "推理"],
    modelId: "grok-4.3",
  },
] satisfies ModelDefinition[];

export const IMAGE_MODELS = [
  {
    id: "liblib-general-image-pro",
    name: "General image Pro",
    provider: "LiblibAI",
    modality: "image",
    description: "最强图片编辑模型，一致性好。",
    availability: "platform",
    tags: ["图片编辑", "一致性", "平台模型"],
    recommended: true,
  },
  {
    id: "liblib-image",
    name: "Lib Image",
    provider: "LiblibAI",
    modality: "image",
    description: "通用图片模型，长文本能力突出。",
    availability: "platform",
    tags: ["通用生图", "长文本", "平台模型"],
  },
  {
    id: "bytedance-seedream-5-pro",
    name: "Seedream 5.0 Pro",
    provider: "字节跳动 Seed",
    modality: "image",
    description: "支持多图融合、参考控制和交互式编辑的高质量档。",
    availability: "api",
    tags: ["多图参考", "编辑", "高质量"],
  },
  {
    id: "liblib-youchuan-v8-1",
    name: "悠船 V8.1",
    provider: "LiblibAI",
    modality: "image",
    description: "生图更连贯、细节更丰富，美学水准大幅提升。",
    availability: "platform",
    tags: ["美学", "细节", "平台模型"],
  },
  {
    id: "openai-gpt-image-2",
    name: "GPT Image 2",
    provider: "OpenAI",
    modality: "image",
    description: "高质量通用生图与编辑模型，支持高保真图像输入。",
    availability: "api",
    tags: ["生成", "编辑", "高保真"],
    modelId: "gpt-image-2",
    recommended: true,
  },
  {
    id: "google-nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "Google",
    modality: "image",
    description: "适合专业资产、复杂布局、精确文字和最高 4K 输出。",
    availability: "api",
    tags: ["4K", "文字渲染", "专业设计"],
    modelId: "gemini-3-pro-image",
    recommended: true,
  },
  {
    id: "google-nano-banana-2",
    name: "Nano Banana 2",
    provider: "Google",
    modality: "image",
    description: "兼顾智能、延迟与成本的高效率生成和编辑模型。",
    availability: "api",
    tags: ["高效率", "编辑", "多参考"],
    modelId: "gemini-3.1-flash-image",
  },
  {
    id: "google-nano-banana-2-lite",
    name: "Nano Banana 2 Lite",
    provider: "Google",
    modality: "image",
    description: "面向高频交互式生图的超低延迟经济档。",
    availability: "api",
    tags: ["低延迟", "低成本", "批量"],
    modelId: "gemini-3.1-flash-lite-image",
  },
  {
    id: "midjourney-v8-1",
    name: "Midjourney V8.1",
    provider: "Midjourney",
    modality: "image",
    description: "注重视觉审美、细节保持和 2K HD 输出的平台模型。",
    availability: "platform",
    tags: ["审美", "2K", "风格化"],
  },
  {
    id: "midjourney-niji-7",
    name: "Niji 7",
    provider: "Midjourney × Spellbrush",
    modality: "image",
    description: "针对动漫、美型角色、线稿和东方插画优化。",
    availability: "platform",
    tags: ["动漫", "插画", "角色"],
  },
  {
    id: "bfl-flux-2-max",
    name: "FLUX.2 Max",
    provider: "Black Forest Labs",
    modality: "image",
    description: "FLUX.2 最高质量档，支持多参考和实时信息 grounding。",
    availability: "api",
    tags: ["最高质量", "多参考", "Grounding"],
    modelId: "flux-2-max",
  },
  {
    id: "bfl-flux-2-pro",
    name: "FLUX.2 Pro",
    provider: "Black Forest Labs",
    modality: "image",
    description: "面向规模化生产的高质量生成与图像编辑模型。",
    availability: "api",
    tags: ["生产级", "写实", "图像编辑"],
    modelId: "flux-2-pro",
  },
  {
    id: "bfl-flux-2-flex",
    name: "FLUX.2 Flex",
    provider: "Black Forest Labs",
    modality: "image",
    description: "突出文字渲染、精细控制和细节保持。",
    availability: "api",
    tags: ["文字", "控制", "细节"],
    modelId: "flux-2-flex",
  },
  {
    id: "bfl-flux-2-klein",
    name: "FLUX.2 Klein",
    provider: "Black Forest Labs",
    modality: "image",
    description: "面向实时和高吞吐场景的亚秒级轻量模型。",
    availability: "api",
    tags: ["亚秒级", "高吞吐", "可本地部署"],
    modelId: "flux-2-klein-9b",
  },
  {
    id: "recraft-v4-1",
    name: "Recraft V4.1",
    provider: "Recraft",
    modality: "image",
    description: "重视版式、品牌调性与可直接用于生产的设计资产。",
    availability: "api",
    tags: ["设计", "品牌", "版式"],
  },
  {
    id: "recraft-v4-1-pro",
    name: "Recraft V4.1 Pro",
    provider: "Recraft",
    modality: "image",
    description: "高分辨率、精细结构和印刷级视觉资产生成。",
    availability: "api",
    tags: ["高分辨率", "印刷", "专业资产"],
  },
  {
    id: "recraft-v4-1-vector",
    name: "Recraft V4.1 Vector",
    provider: "Recraft",
    modality: "image",
    description: "直接生成带结构图层的可编辑 SVG 矢量资产。",
    availability: "api",
    tags: ["SVG", "矢量", "Logo"],
  },
  {
    id: "bytedance-seedream-5-lite",
    name: "Seedream 5.0 Lite",
    provider: "字节跳动 Seed",
    modality: "image",
    description: "兼顾生成速度、成本和多参考编辑能力。",
    availability: "api",
    tags: ["快速", "多参考", "高性价比"],
  },
  {
    id: "alibaba-qwen-image-3-pro",
    name: "Qwen Image 3.0 Pro",
    provider: "阿里云",
    modality: "image",
    description: "适合复杂排版、小字号文字和多语言字体渲染。",
    availability: "api",
    tags: ["复杂排版", "多语言文字", "编辑"],
    modelId: "qwen-image-3.0-pro",
  },
  {
    id: "alibaba-wan-2-7-image-pro",
    name: "Wan 2.7 Image Pro",
    provider: "阿里云",
    modality: "image",
    description: "支持 4K、品牌色、角色一致组图和多图编辑。",
    availability: "api",
    tags: ["4K", "角色一致", "组图"],
    modelId: "wan2.7-image-pro",
    recommended: true,
  },
  {
    id: "alibaba-wan-2-7-image",
    name: "Wan 2.7 Image",
    provider: "阿里云",
    modality: "image",
    description: "保留万相 2.7 核心能力的快速、低成本版本。",
    availability: "api",
    tags: ["快速", "组图", "编辑"],
    modelId: "wan2.7-image",
  },
  {
    id: "kling-image-3",
    name: "Kling Image 3.0",
    provider: "快手可灵",
    modality: "image",
    description: "强调影视级画面表达、角色细节与连续叙事。",
    availability: "api",
    tags: ["影视叙事", "角色", "组图"],
  },
  {
    id: "kling-image-3-omni",
    name: "Kling Image 3.0 Omni",
    provider: "快手可灵",
    modality: "image",
    description: "支持多模态参考和一次生成连贯系列组图。",
    availability: "api",
    tags: ["Omni", "多参考", "系列组图"],
  },
  {
    id: "ideogram-3",
    name: "Ideogram 3.0",
    provider: "Ideogram",
    modality: "image",
    description: "擅长海报、Logo、写实图像和清晰文字排版。",
    availability: "api",
    tags: ["海报", "Logo", "文字"],
  },
  {
    id: "zhipu-glm-image",
    name: "GLM Image",
    provider: "智谱 AI",
    modality: "image",
    description: "面向中文文字渲染与多分辨率视觉生成。",
    availability: "api",
    tags: ["中文文字", "多分辨率", "开源"],
    modelId: "glm-image",
  },
] satisfies ModelDefinition[];

export const VIDEO_MODELS = [
  {
    id: "bytedance-seedance-2",
    name: "Seedance 2.0",
    provider: "字节跳动 Seed",
    modality: "video",
    description: "统一音画联合架构，支持文本、图片、音频和视频参考。",
    availability: "api",
    tags: ["音画同出", "多模态参考", "导演控制"],
    modelId: "seedance2",
    recommended: true,
  },
  {
    id: "bytedance-seedance-2-fast",
    name: "Seedance 2.0 Fast",
    provider: "字节跳动 Seed",
    modality: "video",
    description: "保留关键帧和多参考控制能力的快速生成版本。",
    availability: "api",
    tags: ["快速", "关键帧", "音频"],
    modelId: "seedance2_fast",
  },
  {
    id: "bytedance-seedance-2-mini",
    name: "Seedance 2.0 Mini",
    provider: "字节跳动 Seed",
    modality: "video",
    description: "适合高频迭代与成本敏感工作流的轻量版本。",
    availability: "api",
    tags: ["经济", "快速迭代", "多模态"],
    modelId: "seedance2_mini",
  },
  {
    id: "google-veo-3-1",
    name: "Veo 3.1",
    provider: "Google",
    modality: "video",
    description: "高保真电影级视频，支持原生音频、首尾帧和最高 4K。",
    availability: "preview",
    tags: ["4K", "原生音频", "首尾帧"],
    modelId: "veo-3.1-generate-preview",
    recommended: true,
  },
  {
    id: "google-veo-3-1-fast",
    name: "Veo 3.1 Fast",
    provider: "Google",
    modality: "video",
    description: "面向规模化生产的快速音画生成版本。",
    availability: "preview",
    tags: ["快速", "原生音频", "4K"],
    modelId: "veo-3.1-fast-generate-preview",
  },
  {
    id: "google-veo-3-1-lite",
    name: "Veo 3.1 Lite",
    provider: "Google",
    modality: "video",
    description: "适合开发者高吞吐和低成本场景的视频生成档。",
    availability: "preview",
    tags: ["低成本", "高吞吐", "音频"],
    modelId: "veo-3.1-lite-generate-preview",
  },
  {
    id: "google-gemini-omni-flash",
    name: "Gemini Omni Flash",
    provider: "Google",
    modality: "video",
    description: "通过自然语言连续生成和编辑视频的对话式模型。",
    availability: "preview",
    tags: ["对话编辑", "文生视频", "视频编辑"],
  },
  {
    id: "runway-gen-4-5",
    name: "Runway Gen-4.5",
    provider: "Runway",
    modality: "video",
    description: "高质量文生视频和图生视频，强调镜头控制与稳定运动。",
    availability: "api",
    tags: ["镜头控制", "文生视频", "图生视频"],
    modelId: "gen4.5",
  },
  {
    id: "kling-video-3",
    name: "Kling Video 3.0",
    provider: "快手可灵",
    modality: "video",
    description: "支持原生音频、智能多镜头和最长 15 秒输出。",
    availability: "api",
    tags: ["原生音频", "多镜头", "15 秒"],
    modelId: "kling-v3",
    recommended: true,
  },
  {
    id: "kling-video-3-omni",
    name: "Kling Video 3.0 Omni",
    provider: "快手可灵",
    modality: "video",
    description: "融合主体、图片和视频参考的全模态叙事版本。",
    availability: "api",
    tags: ["Omni", "主体一致", "多模态参考"],
    modelId: "kling-v3-omni",
  },
  {
    id: "alibaba-wan-2-7",
    name: "Wan 2.7",
    provider: "阿里云",
    modality: "video",
    description: "覆盖文生、图生、参考和编辑，支持音画同步与多镜头叙事。",
    availability: "api",
    tags: ["音画同步", "多镜头", "参考视频"],
    modelId: "wan2.7-t2v",
  },
  {
    id: "alibaba-happyhorse-1-1",
    name: "HappyHorse 1.1",
    provider: "阿里云",
    modality: "video",
    description: "支持 1080p、3–15 秒以及文生、图生和参考生视频。",
    availability: "api",
    tags: ["1080p", "带音频", "角色参考"],
    modelId: "happyhorse-1.1-t2v",
  },
  {
    id: "minimax-hailuo-2-3",
    name: "MiniMax Hailuo 2.3",
    provider: "MiniMax",
    modality: "video",
    description: "突出人体运动、表情、物理真实感和提示词遵循。",
    availability: "api",
    tags: ["物理运动", "表情", "1080p"],
    modelId: "MiniMax-Hailuo-2.3",
  },
  {
    id: "minimax-hailuo-2-3-fast",
    name: "MiniMax Hailuo 2.3 Fast",
    provider: "MiniMax",
    modality: "video",
    description: "适合高性价比图生视频的快速版本。",
    availability: "api",
    tags: ["快速", "图生视频", "高性价比"],
    modelId: "MiniMax-Hailuo-2.3-Fast",
  },
] satisfies ModelDefinition[];

export const AUDIO_MODELS = [
  {
    id: "openai-gpt-realtime-2-1",
    name: "GPT-Realtime-2.1",
    provider: "OpenAI",
    modality: "audio",
    audioGroup: "voice",
    description: "支持实时语音输入输出、推理和工具调用的语音 Agent 模型。",
    availability: "api",
    tags: ["实时对话", "语音 Agent", "工具调用"],
    modelId: "gpt-realtime-2.1",
    recommended: true,
  },
  {
    id: "openai-gpt-transcribe",
    name: "GPT Transcribe",
    provider: "OpenAI",
    modality: "audio",
    audioGroup: "voice",
    description: "面向音视频文件的高精度语音转写模型。",
    availability: "api",
    tags: ["语音转文字", "高精度", "字幕"],
    modelId: "gpt-transcribe",
  },
  {
    id: "elevenlabs-eleven-v3",
    name: "Eleven v3",
    provider: "ElevenLabs",
    modality: "audio",
    audioGroup: "voice",
    description: "高情感表现、自然多角色对白和 70+ 语言配音。",
    availability: "api",
    tags: ["情感配音", "多角色", "70+ 语言"],
    modelId: "eleven_v3",
    recommended: true,
  },
  {
    id: "elevenlabs-flash-v2-5",
    name: "Eleven Flash v2.5",
    provider: "ElevenLabs",
    modality: "audio",
    audioGroup: "voice",
    description: "为实时交互优化的约 75ms 低延迟语音合成模型。",
    availability: "api",
    tags: ["低延迟", "实时", "多语言"],
    modelId: "eleven_flash_v2_5",
  },
  {
    id: "elevenlabs-scribe-v2",
    name: "Scribe v2",
    provider: "ElevenLabs",
    modality: "audio",
    audioGroup: "voice",
    description: "支持 90+ 语言、说话人分离和词级时间戳的转写模型。",
    availability: "api",
    tags: ["90+ 语言", "说话人分离", "时间戳"],
    modelId: "scribe_v2",
  },
  {
    id: "google-gemini-3-1-flash-tts",
    name: "Gemini 3.1 Flash TTS",
    provider: "Google",
    modality: "audio",
    audioGroup: "voice",
    description: "支持自然语言风格控制和表现力标签的低延迟 TTS。",
    availability: "preview",
    tags: ["可控 TTS", "表现力", "低延迟"],
    modelId: "gemini-3.1-flash-tts-preview",
  },
  {
    id: "google-gemini-3-1-flash-live",
    name: "Gemini 3.1 Flash Live",
    provider: "Google",
    modality: "audio",
    audioGroup: "voice",
    description: "面向实时对话和 Voice-first 应用的音频到音频模型。",
    availability: "preview",
    tags: ["音频到音频", "实时对话", "多模态"],
    modelId: "gemini-3.1-flash-live-preview",
  },
  {
    id: "alibaba-qwen-audio-3-tts-plus",
    name: "Qwen Audio 3.0 TTS Plus",
    provider: "阿里云",
    modality: "audio",
    audioGroup: "voice",
    description: "支持多语种、音色克隆和自然语言表现控制的高质量 TTS。",
    availability: "api",
    tags: ["音色克隆", "多语种", "表现控制"],
    modelId: "qwen-audio-3.0-tts-plus",
  },
  {
    id: "alibaba-cosyvoice-3-5-plus",
    name: "CosyVoice 3.5 Plus",
    provider: "阿里云",
    modality: "audio",
    audioGroup: "voice",
    description: "同时支持音色克隆、文字描述设计音色和指令控制。",
    availability: "api",
    tags: ["音色设计", "音色克隆", "中文方言"],
    modelId: "cosyvoice-v3.5-plus",
    recommended: true,
  },
  {
    id: "minimax-speech-2-8-hd",
    name: "MiniMax Speech 2.8 HD",
    provider: "MiniMax",
    modality: "audio",
    audioGroup: "voice",
    description: "强调高拟真声音质量、声音标签与音色克隆。",
    availability: "api",
    tags: ["高拟真", "音色克隆", "声音标签"],
    modelId: "speech-2.8-hd",
  },
  {
    id: "minimax-speech-2-8-turbo",
    name: "MiniMax Speech 2.8 Turbo",
    provider: "MiniMax",
    modality: "audio",
    audioGroup: "voice",
    description: "适合实时配音和规模化生成的低延迟版本。",
    availability: "api",
    tags: ["低延迟", "流式", "高吞吐"],
    modelId: "speech-2.8-turbo",
  },
  {
    id: "bytedance-seed-realtime-voice",
    name: "Seed Realtime Voice",
    provider: "字节跳动 Seed",
    modality: "audio",
    audioGroup: "voice",
    description: "端到端融合语音与文本理解和生成的实时语音模型。",
    availability: "platform",
    tags: ["端到端", "实时语音", "对话"],
  },
  {
    id: "google-lyria-3-pro",
    name: "Lyria 3 Pro",
    provider: "Google",
    modality: "audio",
    audioGroup: "music",
    description: "可生成包含主歌、副歌、桥段与人声的完整歌曲。",
    availability: "preview",
    tags: ["完整歌曲", "歌词", "44.1kHz"],
    modelId: "lyria-3-pro-preview",
    recommended: true,
  },
  {
    id: "google-lyria-3-clip",
    name: "Lyria 3 Clip",
    provider: "Google",
    modality: "audio",
    audioGroup: "music",
    description: "用于快速试风格、循环和预览的 30 秒音乐模型。",
    availability: "preview",
    tags: ["30 秒", "快速草稿", "音乐循环"],
    modelId: "lyria-3-clip-preview",
  },
  {
    id: "elevenlabs-music-v2",
    name: "Eleven Music v2",
    provider: "ElevenLabs",
    modality: "audio",
    audioGroup: "music",
    description: "可按自然语言生成并编辑歌曲结构、局部音色和歌词。",
    availability: "api",
    tags: ["结构编辑", "歌词", "多语言"],
    modelId: "music_v2",
  },
  {
    id: "minimax-music-2-6",
    name: "MiniMax Music 2.6",
    provider: "MiniMax",
    modality: "audio",
    audioGroup: "music",
    description: "面向完整歌曲、低频表现和翻唱工作流的音乐模型。",
    availability: "api",
    tags: ["歌曲", "翻唱", "低频表现"],
    modelId: "Music-2.6",
  },
  {
    id: "suno-v5-5",
    name: "Suno v5.5",
    provider: "Suno",
    modality: "audio",
    audioGroup: "music",
    description: "强调动态编曲、清晰人声和个性化音乐风格的平台模型。",
    availability: "platform",
    tags: ["歌曲", "人声", "个性化"],
  },
  {
    id: "bytedance-seed-music",
    name: "Seed Music",
    provider: "字节跳动 Seed",
    modality: "audio",
    audioGroup: "music",
    description: "支持高质量音乐生成和细粒度风格控制的模型套件。",
    availability: "platform",
    tags: ["风格控制", "音乐生成", "创作"],
  },
] satisfies ModelDefinition[];

export const MODEL_GROUPS: Record<ModelModality, ModelDefinition[]> = {
  text: TEXT_MODELS,
  image: IMAGE_MODELS,
  video: VIDEO_MODELS,
  audio: AUDIO_MODELS,
};

export const MODEL_CATALOG = MODEL_GROUPS;

export function getModelsByProvider(provider: string): readonly ModelCatalogItem[] {
  return Object.values(MODEL_GROUPS).flat().filter((model) => model.provider === provider);
}

export function getModelById(id: string): ModelCatalogItem | undefined {
  return Object.values(MODEL_GROUPS).flat().find((model) => model.id === id);
}
