const GLYPHS = {
  add: "\uea60",
  screenFull: "\ueb4c",
  files: "\ueaf0",
  file: "\uea7b",
  info: "\uea74",
  close: "\uea76",
  discard: "\ueae2",
  goToFile: "\uea94",
  trash: "\uea81",
  wrench: "\ueb65",
  sourceControl: "\uea68",
  extensions: "\ueae6",
  deviceCameraVideo: "\uead9",
  beaker: "\uea79",
  layout: "\uebeb",
  layoutPanel: "\uebf2",
  layoutPanelRight: "\uebf1",
  layoutSidebarRight: "\uebf4",
  project: "\ueb30",
  cloudDownload: "\uebd8",
  checklist: "\ueab3",
  warning: "\uea6c",
  search: "\uea6d",
  refresh: "\ueb37",
  zoomIn: "\ueb81",
  zoomOut: "\ueb82",
  map: "\uec05",
  clearAll: "\ueabf",
  collapseAll: "\ueac5",
  caseSensitive: "\ueab1",
  wholeWord: "\ueb7e",
  regex: "\ueb38",
  preserveCase: "\ueb2e",
  replaceAll: "\ueb3c",
  more: "\uea7c",
  sparkle: "\uec10",
  chevronDown: "\ueab4",
  chevronLeft: "\ueab5",
  chevronRight: "\ueab6",
  settingsGear: "\ueb51",
  settings: "\ueb52",
  bell: "\ueaa2",
  symbolFunction: "\uea8c",
  symbolKey: "\uea93",
  symbolClass: "\ueb5b",
  symbolString: "\ueb8d",
} as const;

const CLASS_NAMES = {
  add: "add",
  screenFull: "screen-full",
  files: "files",
  file: "file",
  info: "info",
  close: "close",
  discard: "discard",
  goToFile: "go-to-file",
  trash: "trash",
  wrench: "wrench",
  sourceControl: "source-control",
  extensions: "extensions",
  deviceCameraVideo: "device-camera-video",
  beaker: "beaker",
  layout: "layout",
  layoutPanel: "layout-panel",
  layoutPanelRight: "layout-panel-right",
  layoutSidebarRight: "layout-sidebar-right",
  project: "project",
  cloudDownload: "cloud-download",
  checklist: "checklist",
  warning: "warning",
  search: "search",
  refresh: "refresh",
  zoomIn: "zoom-in",
  zoomOut: "zoom-out",
  map: "map",
  clearAll: "clear-all",
  collapseAll: "collapse-all",
  caseSensitive: "case-sensitive",
  wholeWord: "whole-word",
  regex: "regex",
  preserveCase: "preserve-case",
  replaceAll: "replace-all",
  more: "more",
  sparkle: "sparkle",
  chevronDown: "chevron-down",
  chevronLeft: "chevron-left",
  chevronRight: "chevron-right",
  settingsGear: "settings-gear",
  settings: "settings",
  bell: "bell",
  symbolFunction: "symbol-function",
  symbolKey: "symbol-key",
  symbolClass: "symbol-class",
  symbolString: "symbol-string",
} as const satisfies Record<keyof typeof GLYPHS, string>;

export type CodiconName = keyof typeof GLYPHS;

export function Codicon({ name, className = "" }: { name: CodiconName; className?: string }) {
  const classes = `aa-codicon aa-codicon-${CLASS_NAMES[name]}${className ? ` ${className}` : ""}`;
  return (
    <span className={classes} aria-hidden="true">
      {GLYPHS[name]}
    </span>
  );
}
